[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
fastrand = "2.3.0"
log = "0.4.22"
minifb = "0.27.0"
pretty_env_logger = "0.5.0"
