[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
raylib = "5.0.2"
testing_logger = "0.1.1"
